name: flutter_application_1_ejercicio
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  
flutter:

  assets:
    - Assets/Icons/1.svg
    - Assets/Icons/2.svg
    - Assets/Icons/3.svg 
    - Assets/Icons/r.svg 
    - Assets/img/map/ascent.png
    - Assets/img/map/bind.png
    - Assets/img/map/breeze.png
    - Assets/img/map/icebox.png
    - Assets/img/map/lotus.png
    - Assets/img/map/split.png
    - Assets/img/map/sunset.png
  
  fonts:
     - family: Valorant
       fonts:
         - asset: Assets/fonts/Valorant.ttf

  uses-material-design: true
  